#!/bin/bash

status=`amixer get Master | tail -n1 | grep -wo 'on'`
volume=`amixer get Master | tail -n1 | awk -F ' ' '{print $5}' | tr -d '[]' | sed 's/%//'`

# Get Volume
get_volume_num() {
	if [[ "$status" == "on" ]]; then
        if [[ ($volume -le "9" && $volume -ge "0") ]]; then
            echo "0$volume"
        elif [[ ($volume -eq "100") ]]; then
            echo "99"
        else
            echo "${volume}"
        fi
	else
		echo "00"
	fi
}

get_volume_icon() {
	if [[ "$status" == "on" ]]; then
        if [[ ("$volume" -le "100" && "$volume" -gt "50") ]]; then
            echo ""
        elif [[ ("$volume" -le "50" && "$volume" -ge "0") ]]; then
            echo ""
        fi
	else
		echo ""
	fi
}

# Increase Volume
inc_volume() {
	amixer -Mq set Master,0 5%+ unmute
}

# Decrease Volume
dec_volume() {
	amixer -Mq set Master,0 5%- unmute
}

# Toggle Mute
toggle_mute() {
	status=`amixer get Master | tail -n1 | grep -wo 'on'`

	if [[ "$status" == "on" ]]; then
		amixer set Master toggle
	else
		amixer set Master toggle
	fi
}

# Execute accordingly
if [[ "$1" == "--num" ]]; then
	get_volume_num
elif [[ "$1" == "--icon" ]]; then
	get_volume_icon
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
else
	get_volume_text
fi
